name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v5.0.1
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6.0.0
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Install uv
      uses: astral-sh/setup-uv@v7.1.3
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync
    - name: Prune uv cache
      run: uv cache prune --ci

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v5.0.1
    - name: Install uv
      uses: astral-sh/setup-uv@v7.1.3
      with:
        enable-cache: true
    - name: Install dependencies
      run: uv sync
    - name: Check with editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@v2.1.0
    - name: Spell Check with typos
      uses: crate-ci/typos@v1.39.2
    - name: Install Ruff
      uses: astral-sh/ruff-action@v3.5.1
      with:
        version-file: pyproject.toml
        args: --version
    - name: Check with Ruff
      run: ruff check --output-format=github
    - name: Format with Ruff
      run: ruff format --check --preview --output-format=github
    - name: Type Check with ty
      run: uv run ty check --output-format=github
    - name: Prune uv cache
      run: uv cache prune --ci
