name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14", "3.15"]
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6.0.2
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - name: Install uv
        uses: astral-sh/setup-uv@v7.2.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Prune uv cache
        run: uv cache prune --ci

  check:
    name: Check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6.0.2
      - name: Install Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version-file: pyproject.toml
      - name: Install uv
        uses: astral-sh/setup-uv@v7.2.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync
      - name: Check with editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@v2.1.0
      - name: Spell Check with typos
        uses: crate-ci/typos@v1.42.3
      - name: Install Ruff
        uses: astral-sh/ruff-action@v3.5.1
        with:
          version-file: pyproject.toml
          args: --version
      - name: Check with Ruff
        run: ruff check --output-format=github
      - name: Format with Ruff
        run: ruff format --check --preview --output-format=github
      - name: Type Check with ty
        run: uv run ty check --output-format=github
      - name: Prune uv cache
        run: uv cache prune --ci
